# Generated by Django 3.0.7 on 2020-06-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200617_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dt',
        ),
    ]
